DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS ipaddr;

CREATE TABLE user(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  user_role TEXT NOT NULL,
  first_login INTEGER NOT NULL
);
CREATE TABLE ipaddr(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ipaddress TEXT NOT NULL,
  userid INTEGER NOT NULL,
  FOREIGN KEY(userid) REFERENCES user(id)
);